### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by JosephPai** [neuroailab/LocalAggregation#1]
Hi, many thanks for releasing source code of the amazing work.

I wonder would you like to release the LA for IR pre-trained model?

Warm up training on ImageNet is hard and time consuming for an individual.

Thanks.

**Comment by chengxuz** [comment]
Hi Zechen,

Thanks for your interest in this project.

LA algorithm starts from a model trained on ImageNet using IR algorithm for 10 epochs, which only takes like several hours. The majority of the training is still using LA algorithm. And we provide both IR and LA implementations in our codes.

Please let me know if you have any further questions.

**Comment by JosephPai** [comment]
ok I'll try it.

Thank you.
