### ISSUE TITLE
Published Pretrained Models

### ISSUE THREAD

**Issue by AhmadM-DL** [neuroailab/LocalAggregation#4]
Hello,
Are there any published pretrained models?

**Comment by chengxuz** [comment]
Thanks for asking. This is what I found: `http://visualmaster-models.s3.amazonaws.com/la_orig/checkpoint-1901710.tar`. This is a pretrained ResNet-18 by Local Aggregation. However, this model may not be as good as a fully trained model by this repo, I believe it's a slightly earlier checkpoint than the final one.

**Comment by AhmadM-DL** [comment]
Thanks  @chengxuz
